# Pandas的函数应用

In [2]:
import pandas as pd
import numpy as np

# randn跟的是维数，5行4列
df = pd.DataFrame(np.random.randn(5, 4) - 1)
print(df)
print('-' * 50)

# absolute(绝对值)
print(np.abs(df))

          0         1         2         3
0 -1.331576 -0.641853 -0.081319 -1.246258
1 -0.503591 -0.772694  0.971282 -1.093298
2 -0.681250 -1.061134 -0.570409  0.673149
3 -1.833001 -1.465694 -1.592963 -0.702816
4 -1.386766 -0.054349 -1.168638 -0.219808
--------------------------------------------------
          0         1         2         3
0  1.331576  0.641853  0.081319  1.246258
1  0.503591  0.772694  0.971282  1.093298
2  0.681250  1.061134  0.570409  0.673149
3  1.833001  1.465694  1.592963  0.702816
4  1.386766  0.054349  1.168638  0.219808

In [3]:
# apply默认作用在列上，因为axis=0，x依次代表每一列（Series）；x.max()求该列最大值；返回：每列最大值组成的Series，索引=列名
# df.apply(lambda x: x.max()) -> df.max()
# apply：DataFrame的核心方法，用于对指定轴（行/列）批量应用自定义函数
print(df.apply(lambda x: x.max()))

0   -0.503591
1   -0.054349
2    0.971282
3    0.673149
dtype: float64

In [4]:
"""
lambda x: x.max()
->
def func(x):
    return x.max()
"""
# apply作用在行上
print(df.apply(lambda x: x.max(), axis=1))

0   -0.081319
1    0.971282
2    0.673149
3   -0.702816
4   -0.054349
dtype: float64

In [6]:
print(df)
# round(x, 2)   对x四舍五入保留2位小数
print(df.map(lambda x: f'{x:.2f}'))
df.dtypes

          0         1         2         3
0 -1.331576 -0.641853 -0.081319 -1.246258
1 -0.503591 -0.772694  0.971282 -1.093298
2 -0.681250 -1.061134 -0.570409  0.673149
3 -1.833001 -1.465694 -1.592963 -0.702816
4 -1.386766 -0.054349 -1.168638 -0.219808
       0      1      2      3
0  -1.33  -0.64  -0.08  -1.25
1  -0.50  -0.77   0.97  -1.09
2  -0.68  -1.06  -0.57   0.67
3  -1.83  -1.47  -1.59  -0.70
4  -1.39  -0.05  -1.17  -0.22

0    float64
1    float64
2    float64
3    float64
dtype: object

In [7]:
ser = pd.Series(['male','female','male'])
print(ser.map({'male':1, 'female':0}))

0    1
1    0
2    1
dtype: int64

In [8]:
type(f'{1.3456:.2f}')

str

# 6.4 索引排序

In [11]:
# Series
# 在区间[0, 5)之间随机生成5个整数
print(np.random.randint(5, size=5))
print('-' * 50)
s4 = pd.Series(range(10, 15), index=np.random.randint(5, size=5))           # 索引随机生成
print(s4)
print('-' * 50)
# 索引排序，sort_index返回一个新的排好索引的series
print(s4.sort_index())
print(s4)
print('-' * 50)

# s4.loc[0: 3]  loc索引值不唯一时也报错
# 按索引值下标取值 iloc：左闭右开；loc：左闭右闭
print(s4.iloc[0: 3])
s4[0: 3]        # 默认用的位置索引  s4[0: 3] -> s4.iloc[0: 3]

[2 1 1 3 3]
--------------------------------------------------
2    10
4    11
1    12
4    13
1    14
dtype: int64
--------------------------------------------------
1    12
1    14
2    10
4    11
4    13
dtype: int64
2    10
4    11
1    12
4    13
1    14
dtype: int64
--------------------------------------------------
2    10
4    11
1    12
dtype: int64

2    10
4    11
1    12
dtype: int64

In [9]:
# 区间[0, 8)之间随机生成4个整数
print(np.random.randint(8, size= 4))

[6 3 5 0]

In [12]:
# s4.loc[1: 2]      loc索引值唯一时可以切片

In [17]:
# DataFrame
df4 = pd.DataFrame(np.random.randn(5, 5), index=np.random.randint(5, size=5), columns=np.random.randint(5, size=5))
print(df4)
print('-' * 100)
# 轴0是行索引排序
df4_isort = df4.sort_index(axis=0, ascending=True)
print(df4_isort)

          2         0         4         0         1
3 -0.002731 -1.145842  0.068259  0.596929  0.126171
0 -0.624647 -1.983434  0.335379 -0.156836  1.330752
2 -0.592211 -1.160413  0.303704 -0.043646 -2.782945
2 -0.279427  0.498002 -0.322976 -0.264071 -0.631706
2 -0.812975 -0.904332  1.100526 -0.335450  1.886808
----------------------------------------------------------------------------------------------------
          2         0         4         0         1
0 -0.624647 -1.983434  0.335379 -0.156836  1.330752
2 -0.592211 -1.160413  0.303704 -0.043646 -2.782945
2 -0.279427  0.498002 -0.322976 -0.264071 -0.631706
2 -0.812975 -0.904332  1.100526 -0.335450  1.886808
3 -0.002731 -1.145842  0.068259  0.596929  0.126171

In [18]:
# 轴1是列索引排序
df4_isort = df4.sort_index(axis=1, ascending=True)
print(df4_isort)

          0         0         1         2         4
3 -1.145842  0.596929  0.126171 -0.002731  0.068259
0 -1.983434 -0.156836  1.330752 -0.624647  0.335379
2 -1.160413 -0.043646 -2.782945 -0.592211  0.303704
2  0.498002 -0.264071 -0.631706 -0.279427 -0.322976
2 -0.904332 -0.335450  1.886808 -0.812975  1.100526

# 6.5 按值排序（机器学习、深度学习不重要，数据分析才重要）

In [20]:
# 按值排序，by 后是 column 的值
import random
l = [random.randint(0, 100) for i in range(24)]         # 生成24个随机数
df4 = pd.DataFrame(np.array(l).reshape(6, 4))           # 生成6行4列的DataFrame
print(df4)
print('-' * 50)

# 给轴0重新排序，根据 by=3 即下标为3的列的数据按从大到小的顺序排序
df4_vsort = df4.sort_values(by=3, axis=0, ascending=False)      # 寻找的是columns里的3，重要
print(df4_vsort)

    0   1   2   3
0  54   2   9  53
1  67  96   6  29
2  30  10  34  54
3  30  31  13  24
4  89   5  35  68
5  26  15  39  54
--------------------------------------------------
    0   1   2   3
4  89   5  35  68
2  30  10  34  54
5  26  15  39  54
0  54   2   9  53
1  67  96   6  29
3  30  31  13  24

In [21]:
# 按轴1排序，by后行索引名，交换的是列
df4_vsort = df4.sort_values(by=3, axis=1, ascending=False)      # 寻找的是index里的3
print(df4_vsort)

    1   0   3   2
0   2  54  53   9
1  96  67  29   6
2  10  30  54  34
3  31  30  24  13
4   5  89  68  35
5  15  26  54  39

# 6.6 处理缺失数据（重要）

In [22]:
df_data = pd.DataFrame([np.random.randn(3), [1., 2., np.nan], [np.nan, 4., np.nan], [1., 2., 3.]])
print(df_data.head())

          0       1         2
0  0.813623  0.5773 -1.338747
1  1.000000  2.0000       NaN
2       NaN  4.0000       NaN
3  1.000000  2.0000  3.000000

In [23]:
df_data.iloc[2, 0]

np.float64(nan)

In [24]:
# isnull 来判断是否有空的数据
print(df_data.isnull())

       0      1      2
0  False  False  False
1  False  False   True
2   True  False   True
3  False  False  False

In [28]:
# .sum()：默认axis=0，按列求和，True=1，False=0；结果：每一列缺失值总个数（Series，索引=列名）
print(df_data.isnull().sum())
print('-' * 50)
# len(df_data)：返回DataFrame的总行数
print(len(df_data))
print('-' * 50)
print(df_data.isnull().sum() / len(df_data))

0    1
1    0
2    2
dtype: int64
--------------------------------------------------
4
--------------------------------------------------
0    0.25
1    0.00
2    0.50
dtype: float64

# 删除缺失数据

In [29]:
# 删除第0列含有缺失值的所有行    dropna()：删除存在缺失值的行；subset=[0]：只检查第0列（列位置为0），其他列有没有缺失不管
# subset里面写数字代表列位置；如果你的列有名字，更常用列名字符串
print(df_data.dropna(subset=[0]))
df_data

          0       1         2
0  0.813623  0.5773 -1.338747
1  1.000000  2.0000       NaN
3  1.000000  2.0000  3.000000

          0       1         2
0  0.813623  0.5773 -1.338747
1  1.000000  2.0000       NaN
2       NaN  4.0000       NaN
3  1.000000  2.0000  3.000000

In [30]:
print(df_data.dropna(axis=1))           # 某列有nan就删除该列

        1
0  0.5773
1  2.0000
2  4.0000
3  2.0000

 # 填充缺失数据

In [32]:
# 给0列的空值填为-100，按特征（按列）去填充
print(df_data.iloc[:, 0].fillna(-100.))
df_data

0      0.813623
1      1.000000
2   -100.000000
3      1.000000
Name: 0, dtype: float64

          0       1         2
0  0.813623  0.5773 -1.338747
1  1.000000  2.0000       NaN
2       NaN  4.0000       NaN
3  1.000000  2.0000  3.000000

In [34]:
for i in df_data.columns:
    print(df_data.loc[:, i])
    print('-' * 50)

0    0.813623
1    1.000000
2         NaN
3    1.000000
Name: 0, dtype: float64
--------------------------------------------------
0    0.5773
1    2.0000
2    4.0000
3    2.0000
Name: 1, dtype: float64
--------------------------------------------------
0   -1.338747
1         NaN
2         NaN
3    3.000000
Name: 2, dtype: float64
--------------------------------------------------

In [37]:
# 用均值填充空值
df_data.iloc[:, 2] = df_data.iloc[:, 2].fillna(df_data.iloc[:, 2].mean())

In [38]:
df_data

          0       1         2
0  0.813623  0.5773 -1.338747
1  1.000000  2.0000  0.830626
2       NaN  4.0000  0.830626
3  1.000000  2.0000  3.000000