# 数据连接

In [3]:
import pandas as pd
import numpy as np

df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 
                        'data1': np.random.randint(0, 10, 7)})
df_obj2 = pd.DataFrame({'key': ['a', 'b', 'd'], 
                        'data2': np.random.randint(0, 10, 3)})

print(df_obj1)
print('-' * 50)
print(df_obj2)
print(type(df_obj2))                # <class 'pandas.DataFrame'>

  key  data1
0   b      0
1   b      2
2   a      5
3   c      0
4   a      1
5   a      5
6   b      0
--------------------------------------------------
  key  data2
0   a      9
1   b      4
2   d      9
<class 'pandas.DataFrame'>

In [4]:
# 默认连接使用相同的列名，连接方式是内连接（只保留两边都匹配的数据）
pd.merge(df_obj1, df_obj2)

  key  data1  data2
0   b      0      4
1   b      2      4
2   a      5      9
3   a      1      9
4   a      5      9
5   b      0      4

In [5]:
# 把左右索引作连接键join，因为df_obj2只有三行数据，故index索引只有三行
pd.merge(df_obj1, df_obj2, left_index=True, right_index=True)

  key_x  data1 key_y  data2
0     b      0     a      9
1     b      2     b      4
2     a      5     d      9

In [6]:
# 内连接，保留两边都匹配的数据
pd.merge(df_obj1, df_obj2, on='key')

  key  data1  data2
0   b      0      4
1   b      2      4
2   a      5      9
3   a      1      9
4   a      5      9
5   b      0      4

In [7]:
df_obj1 = df_obj1.rename(columns={'key': 'key1'})
df_obj2 = df_obj2.rename(columns={'key': 'key2'})

In [9]:
df_obj1

  key1  data1
0    b      0
1    b      2
2    a      5
3    c      0
4    a      1
5    a      5
6    b      0

In [10]:
df_obj2

  key2  data2
0    a      9
1    b      4
2    d      9

In [11]:
# 两张表连接键名字不一样时使用：left_on='key1'：左表df_obj1拿key1这一列作为连接键；right_on='key2'：右表df_obj2拿key2这一列作为连接键
# 如果两表键同名，直接写 on='key'；名字不同，必须分开写 left_on/right_on
# 保留两边都匹配的数据
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2')

  key1  data1 key2  data2
0    b      0    b      4
1    b      2    b      4
2    a      5    a      9
3    a      1    a      9
4    a      5    a      9
5    b      0    b      4

In [12]:
# 全外连接，取左表 key1 集合 ∪ 右表 key2 集合（并集）
# 1. 两边都能匹配上的行：正常合并，数值都保留
# 2. 只在左表存在，右表无匹配：右表字段填充NaN
# 3. 只在右表存在，左表无匹配：左表字段填充NaN
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2', how='outer')

  key1  data1 key2  data2
0    a    5.0    a    9.0
1    a    1.0    a    9.0
2    a    5.0    a    9.0
3    b    0.0    b    4.0
4    b    2.0    b    4.0
5    b    0.0    b    4.0
6    c    0.0  NaN    NaN
7  NaN    NaN    d    9.0

In [13]:
# 左外连接（只关心左表全部数据，丢失右表独有的行）
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2', how='left')

  key1  data1 key2  data2
0    b      0    b    4.0
1    b      2    b    4.0
2    a      5    a    9.0
3    c      0  NaN    NaN
4    a      1    a    9.0
5    a      5    a    9.0
6    b      0    b    4.0

In [14]:
# 右外连接（不一定右表只有三行所以连接后就只有三行）
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2', how='right')

  key1  data1 key2  data2
0    a    5.0    a      9
1    a    1.0    a      9
2    a    5.0    a      9
3    b    0.0    b      4
4    b    2.0    b      4
5    b    0.0    b      4
6  NaN    NaN    d      9

In [15]:
# np.random.randint(low, high, size)：low：下界（包含）；high：上界（不包含）；size：生成多少个数字
df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 
                        'data': np.random.randint(0, 10, 7)})               # 左闭右开
df_obj2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                        'data': np.random.randint(0, 10, 3)})
# 给相同的数据列添加后缀
print(pd.merge(df_obj1, df_obj2, on='key', suffixes=('_left', '_right')))

  key  data_left  data_right
0   b          1           7
1   b          2           7
2   a          2           3
3   a          3           3
4   a          2           3
5   b          1           7

In [16]:
# 按索引连接
df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data1': np.random.randint(0, 10, 7)})
df_obj2 = pd.DataFrame({'data2': np.random.randint(0, 10, 3)}, index=['a', 'b', 'd'])
print(df_obj1)
print('-' * 50)
print(df_obj2)

  key  data1
0   b      4
1   b      2
2   a      7
3   c      7
4   a      8
5   a      6
6   b      2
--------------------------------------------------
   data2
a      1
b      9
d      0

In [17]:
# left_on='key'：左表df_obj1 -> 使用普通列 key 作为连接键
# right_index=True：右表 df_obj2 -> 使用行索引作为连接键
# 默认 how='inner'（内连接）
# 以df1为主，拿df1.key去匹配df2的索引
print(pd.merge(df_obj1, df_obj2, left_on='key', right_index=True))

  key  data1  data2
0   b      4      9
1   b      2      9
2   a      7      1
4   a      8      1
5   a      6      1
6   b      2      9

In [18]:
# 以df2为主，拿df2的索引去匹配df1.key，所以前三行都为a
pd.merge(df_obj2, df_obj1, left_index=True, right_on='key')

   data2 key  data1
2      1   a      7
4      1   a      8
5      1   a      6
0      9   b      4
1      9   b      2
6      9   b      2